--[[
* @file : GameCfg.lua
* @type : lualib
* @author : linfeng
* @created : Thu Nov 23 2017 17:21:37 GMT+0800 (中国标准时间)
* @department : Arabic Studio
* @brief : game_server 的数据配置文件
* Copyright(C) 2017 IGG, All rights reserved
]]

ConfigEntityCfg = {
	{ name = "s_BuildingArcheryrange", key = "ID", noreload = true },
	{ name = "s_BuildingBarracks", key = "ID", noreload = true },
	{ name = "s_BuildingLevelData", key = "ID" },
	{ name = "s_BuildingSiegeWorkshop", key = "ID", noreload = true },
	{ name = "s_BuildingStable", key = "ID", noreload = true },
	{ name = "s_BuildingStorage", key = "ID" },
	{ name = "s_Civilization", key = "ID" },
	{ name = "s_BuildingTownCenter", key = "ID", noreload = true },
	{ name = "s_BuildingCityWall", key = "ID", noreload = true },
	{ name = "s_BuildingGuardTower", key = "ID", noreload = true },
	{ name = "s_BuildingCampus", key = "ID", noreload = true },
	{ name = "s_BuildingHospital", key = "ID", noreload = true },
	{ name = "s_BuildingCastle", key = "ID", noreload = true },
	{ name = "s_BuildingScoutcamp", key = "ID", noreload = true },
	{ name = "s_Hero", key = "ID" },
	{ name = "s_HeroLevel", key = "ID", noreload = true },
	{ name = "s_Config", key = "ID" },
	{ name = "s_HeroSkillEffect", key = "ID" },
	{ name = "s_HeroTalentGainTree", key = "ID" },
	{ name = "s_TaskMain", key = "ID" },
	{ name = "s_TaskSide", key = "ID" },
	{ name = "s_TaskDaily", key = "ID" },
	{ name = "s_TaskChapter", key = "ID" },
	{ name = "s_BuildingResourcesProduce", key = "ID", noreload = true },
	{ name = "s_ItemPackage", key = "ID", noreload = true },
	{ name = "s_Study", key = "ID" },
	{ name = "s_Arms", key = "ID" },
	{ name = "s_ZeroEmpty", key = "ID", noreload = true },
	{ name = "s_CityAgeSize", key = "ID"},
	{ name = "s_BuildingTypeConfig", key = "ID"},
	{ name = "s_BuildingCountLimit", key = "ID"},
	{ name = "s_ResourceGatherType", key = "ID" },
	{ name = "s_ResourceGatherRule", key = "ID", noreload = true },
	{ name = "s_ResourceGatherPoint", key = "ID", noreload = true },
	{ name = "s_InitBuilding", key = "ID" },
	{ name = "s_Mail", key = "ID" },
	{ name = "s_TaskChapterData", key = "ID" },
	{ name = "s_Item", key = "ID" },
	{ name = "s_Monster", key = "ID" },
	{ name = "s_MonsterRefreshLevel", key = "ID", noreload = true },
	{ name = "s_MonsterPoint", key = "ID", noreload = true },
	{ name = "s_instantPrice", key = "ID" },
	{ name = "s_BuildingAllianceCenter", key = "ID", noreload = true },
	{ name = "s_MonsterTroops", key = "ID" },
	{ name = "s_MonsterTroopsAttr", key = "ID", noreload = true },
	{ name = "s_MapFixPoint", key = "ID", noreload = true },
	{ name = "s_MonsterZoneLevel", key = "ID" },
	{ name = "s_ResourceZoneLevel", key = "ID" },
	{ name = "s_VillageRewardData", key = "ID", noreload = true },
	{ name = "s_MapZoneSF", key = "ID" },
	{ name = "s_SquareSpacing", key = "ID" },
	{ name = "s_SquareNumberBySum", key = "ID" },
	{ name = "s_SquareMaxNumber", key = "ID" },
	{ name = "s_BuildingMail", key = "ID", noreload = true },
	{ name = "s_BuildingTavern", key = "ID", noreload = true },
	{ name = "s_TaskActivityReward", key = "ID", noreload = true },
	{ name = "s_Block", key = "ID" },
	{ name = "s_ActivityCalendar", key = "ID" },
	{ name = "s_HeroSkillLevel", key = "ID", noreload = true },
	{ name = "s_HeroSkill", key = "ID" },
	{ name = "s_AllianceMember", key = "ID", noreload = true },
	{ name = "s_AllianceMemberJurisdiction", key = "ID", noreload = true },
	{ name = "s_AllianceOfficially", key = "ID" },
	{ name = "s_CityBuff", key = "ID" },
	{ name = "s_CityBuffGroup", key = "ID" },
	{ name = "s_CityBuffSeries", key = "ID" },
	{ name = "s_HeroStar", key = "ID" },
	{ name = "s_ActivityTargetType", key = "ID" },
	{ name = "s_HeroStarExp", key = "ID", noreload = true },
	{ name = "s_PlayerHead", key = "ID" },
	{ name = "s_ItemPlayerHead", key = "ID" },
	{ name = "s_AllianceBuildingType", key = "ID", noreload = true },
	{ name = "s_AllianceBuildingData", key = "ID", noreload = true },
	{ name = "s_ActivityDropType", key = "ID" },
	{ name = "s_BattleBuff", key = "ID" },
	{ name = "s_Leaderboard", key = "ID" },
	{ name = "s_ActivityEndHanding", key = "ID" },
	{ name = "s_ActivityConversionType", key = "ID" },
	{ name = "s_ActivityDaysType", key = "ID" },
	{ name = "s_MysteryStore", key = "ID" },
	{ name = "s_MysteryStorePro", key = "ID", noreload = true },
	{ name = "s_AllianceSign", key = "ID" },
	{ name = "s_ActivityKillType", key = "ID" },
	{ name = "s_ActivityKillIntegral", key = "ID" },
	{ name = "s_ActivityRankingType", key = "ID", noreload = true },
	{ name = "s_ResourcesPlunderLoss", key = "ID" },
	{ name = "s_SkillBattle", key = "ID" },
	{ name = "s_ItemRewardChoice", key = "ID", noreload = true },
	{ name = "s_VipAtt", key = "ID", noreload = true },
	{ name = "s_Vip", key = "ID", noreload = true },
	{ name = "s_VipDayPoint", key = "ID" },
	{ name = "s_RechargeGemMall", key = "ID" },
	{ name = "s_RechargeDailySpecial", key = "ID" },
	{ name = "s_EvolutionMileStone", key = "ID", noreload = true },
	{ name = "s_RechargeSale", key = "ID" },
	{ name = "s_RechargeFirst", key = "ID" },
	{ name = "s_RechargeFund", key = "ID" },
	{ name = "s_RechargeSupply", key = "ID" },
	{ name = "s_RechargeLimitTimeBag", key = "ID" },
	{ name = "s_RallyTimes", key = "ID" },
	{ name = "s_BuildingFreight", key = "ID", noreload = true },
	{ name = "s_ExpeditionHead", key = "ID" },
	{ name = "s_ExpeditionShop", key = "ID" },
	{ name = "s_Price", key = "ID" },
	{ name = "s_EvolutionRankReward", key = "ID", noreload = true },
	{ name = "s_MonsterDamageReward", key = "ID" },
	{ name = "s_MonsterLootRule", key = "ID", noreload = true },
	{ name = "s_ActivityInfernal", key = "ID" },
	{ name = "s_StrongHoldType", key = "ID" },
	{ name = "s_StrongHoldData", key = "ID", noreload = true },
	{ name = "s_VipStore", key = "ID" },
	{ name = "s_EquipMaterial", key = "ID", noreload = true },
	{ name = "s_Equip", key = "ID", noreload = true },
	{ name = "s_UnitView", key = "ID" },
	{ name = "s_MapItemType", key = "ID" },
	{ name = "s_AllianceStudy", key = "ID", noreload = true },
	{ name = "s_AllianceDonateRanking", key = "ID", noreload = true },
	{ name = "s_ActivityReapType", key = "ID", noreload = true },
	{ name = "s_HeroTalent", key = "ID" },
	{ name = "s_SystemOpen", key = "ID" },
	{ name = "s_HeroTalentMastery", key = "ID", noreload = true },
	{ name = "s_ChatChannel", key = "ID" },
	{ name = "s_AllianceGiftReward", key = "ID" },
	{ name = "s_AllianceTreasure", key = "ID" },
	{ name = "s_AllianceGiftLevel", key = "ID" },
	{ name = "s_AllianceGiftType", key = "ID" },
	{ name = "s_EquipAtt", key = "ID" },
	{ name = "s_EquipCompose", key = "ID" },
	{ name = "s_MailLevelLimit", key = "ID" },
	{ name = "s_PushMessageData", key = "ID" },
	{ name = "s_PushMessageGroup", key = "ID" },
	{ name = "s_LanguageServer", key = "ID" },
	{ name = "s_BattleMail", key = "ID" },
	{ name = "s_AllianceShopItem", key = "itemType" },
	{ name = "s_ChatBlock", key = "ID" },
	{ name = "s_Expedition", key = "ID" },
	{ name = "s_ExpeditionBattle", key = "ID" },
	{ name = "s_SkillStatus", key = "ID" },
	{ name = "s_MapBarrierConnect", key = "ID" },
	{ name = "s_CityHideData", key = "ID", noreload = true },
	{ name = "s_Guide", key = "ID" },
	{ name = "s_ActivityIntegralType", key = "ID", noreload = true },
	{ name = "s_MapMarkerType", key = "ID" },
	{ name = "s_GameWarning", key = "ID" },
	{ name = "s_ActivityNewPlayer", key = "ID" },
	{ name = "s_TurntableDraw", key = "ID", noreload = true },
	{ name = "s_TurntableDrawProgress", key = "ID" },
	{ name = "s_TurntableDrawRange", key = "ID" },
	{ name = "s_AbTest", key = "ID" },
	{ name = "s_BattleDamageCompensation", key = "ID" },
	{ name = "s_EvolutionGoalFillData", key = "ID" }
}

CommonEntityCfg = {
	{ name = "c_pkid", key = "id", value = "value" },
	{ name = "c_map_object", key = "id", value = "value", db = true },
	{ name = "c_refresh", key = "id", value = "value", db = true },
	{ name = "c_guild", key = "guildId", value = "value", center = true },
	{ name = "c_activity", key = "id", value = "value", db = true },
	{ name = "c_guild_building", key = "guildId", value = "value", attr = "buildInfo", mainIndex = "buildIndex", db = true },
	{ name = "c_role_power", key = "rid", value = "value", db = true },
	{ name = "c_alliance_power", key = "guildId", value = "value", db = true },
	{ name = "c_alliance_kill", key = "guildId", value = "value", db = true },
	{ name = "c_alliance_flag", key = "guildId", value = "value", db = true },
	{ name = "c_townhall", key = "rid", value = "value", db = true },
	{ name = "c_role_kill", key = "rid", value = "value", db = true },
	{ name = "c_role_collect_res", key = "rid", value = "value", db = true },
	{ name = "c_reserve", key = "rid", value = "value", db = true },
	{ name = "c_combat_first", key = "rid", value = "value", db = true },
	{ name = "c_rise_up", key = "rid", value = "value", db = true },
	{ name = "c_kill_type", key = "id", value = "value", db = true },
	{ name = "c_kill_type_history", key = "id", value = "value", db = true },
	{ name = "c_monument", key = "id", value = "value", db = true },
	{ name = "c_expedition", key = "rid", value = "value", db = true },
	{ name = "c_expeditionShop", key = "id", value = "value", db = true },
	{ name = "c_holy_land", key = "id", value = "value", db = true },
	{ name = "c_king", key = "id", value = "value", db = true },
	{ name = "c_system", key = "id", value = "value", db = true },
	{ name = "c_systemmail", key = "id", value = "value", db = true },
	{ name = "c_guild_message_board", key = "guildId", value = "value", attr = "messageInfo", mainIndex = "messageIndex", db = true },
	{ name = "c_guild_gift", key = "guildId", value = "value", attr = "giftInfo", mainIndex = "giftIndex", db = true },
	{ name = "c_guild_role_power", key = "guildId", value = "value", attr = "rolePowerInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_role_kill", key = "guildId", value = "value", attr = "roleKillInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_role_donate", key = "guildId", value = "value", attr = "roleDonateInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_role_build", key = "guildId", value = "value", attr = "roleBuildInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_role_help", key = "guildId", value = "value", attr = "roleHelpInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_resource_help", key = "guildId", value = "value", attr = "resourceHelpInfo", mainIndex = "rid", db = true },
	{ name = "c_guild_shop", key = "guildId", value = "value", db = true },
	{ name = "c_recharge", key = "id", value = "value", db = true },
	{ name = "c_tribe_king", key = "guildId", value = "value", db = true },
	{ name = "c_fight_horn", key = "rid", value = "value", db = true },
	{ name = "c_fight_horn_alliance", key = "guildId", value = "value", db = true },
}

UserEntityCfg = {

}

RoleEntityCfg = {
	{ name = "d_role", key = "rid", value = "value", db = true },
	{ name = "d_user", key = "uid", value = "value", db = true, noLoad = true },
	{ name = "d_building", key = "rid", value = "value", attr = "buildInfo", mainIndex = "buildIndex", db = true },
	{ name = "d_item", key = "rid", value = "value", attr = "itemInfo", mainIndex = "itemIndex", db = true },
	{ name = "d_email", key = "rid", value = "value", attr = "emailInfo", mainIndex = "emailIndex", db = true },
	{ name = "d_hero", key = "rid", value = "value", attr = "heroInfo", mainIndex = "heroId", db = true },
	{ name = "d_army", key = "rid", value = "value", attr = "armyInfo", mainIndex = "armyIndex", db = true },
	{ name = "d_scouts", key = "rid", value = "value", attr = "scoutsInfo", mainIndex = "scoutsIndex", db = true },
	{ name = "d_task", key = "rid", value = "value", attr = "taskInfo", mainIndex = "taskId", db = true },
	{ name = "d_transport", key = "rid", value = "value", attr = "transportInfo", mainIndex = "transportIndex", db = true },
	{ name = "d_chat", key = "rid", value = "value", attr = "privateChatInfo", mainIndex = "rid", db = true },
}
